install: gradle wrapper --gradle-version 4.2
language: groovy
jdk:
- oraclejdk8
dist: trusty
sudo: false
branches:
  only:
  - master
  - master-pure
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: EI6qIU/2FtyUuyksfPM2QlMb3+T5Lt4MieH3v9C2Xy9uISa5aNRznbOPTroOfWCLC6rpdv7ic622L02tXry4YOO14SfbJVEqTzpg3XdnXfRBwESiIwAUEuc1EbQIv50gfeWc2N+8KzAJxv1ZNoQgCQXj37b3nJIIdfHnUKn6hGOiGLdngx2zDx7qBuUxhU+3Bcd6hqTtcEC8FAGy+66RZM1B8GKtB5opSC4Y3tYYlfCsqF8dgeKlqYwhVQqZ4Pnh8clTPD2NSfs6q0o3j4W3HWiKrmvRvd1KbNVHNCeHQDQhBSmWkpEftWhC5B0oIecQP7qZGGJn3nUJ2SZv2qYox/3TP2NTHUMpNVH1bC6M7ru6wv8os3eEdYvzMoJNlO6TXqKRuTiNxuDA745iaV3qa9Q3lXVHiOAvoFH6dlf6699QKJZrxKCnXb95hLKQTyX73nJOP5UDBbrXBK8G841oervNTprNhGHoXLXLiV9VBe4Fx/X5cD1/Y/7B6gEbV6lcIyQcB1rihAE4mNKimiVWPj8TvvDN9YNdBDVlflZQHdso85Lr24WptflOmaS8NN6IUf5asIMM0pEVuJpjHQuWvN99u8y4B5eWrPJjl9TUR510nGT56n66YosUM76ctlV8Ls5zD2SIN8uYjZSpCbf1HJU9oQ6yaDG+RTNkc23Iy8o=
  - secure: zL0fleuLhbUGz4jeVCyxs+gaLtx4P1E2kv/9cmtOZSPfY2mJ8nV3eMECPCaHH3LyJPf5TtwiuBXearOeBIIz5zYzfITr+InNw1F7Ptm3l17NK5Hkhv/6CuGC2Rdew30sdvC5oBf8jsQS8UPhc1aSzybmUuV42775mIvbTowlyy2ALJbVxBspbzQVDBHVbeMDJnIixgL/RR9gdHgaam1yHmq0m1/UUKt0JU/3QwRu9Wb+lub75dZGevWnZv2PprF2p2icAACHRwF9JmhQ8U7r131PZ8/6iy8Jhy0fnsVplQEqeOiEMO0b/ty7bEF8osEtiW19M9LSyEuKjeTSbbAjDALP6Dye7yqV6HuNgsd7MHCtoidmhPD+WxMK28+dTaaHCC+R9gV9Y89hbDdWCLhwtZboWrJ1+IqhUM5C/tQtjYKmQjxxR7ing6horXHxkYI8MzT7q8KHC0Cd5jlzXkwe7hJQ5JURdcKTdlbtXzIsOBqPudpLSL6kY6U810AcMNpHpmWFKDyYdlzjrUST/tBITOzS9pzfPsmh5ummjP+gufTScL6MhLBwDcpbYugQIvqelb5SaVuSpqIK9ufLvbSQCvgD/ADp9nlQZCaxKHxdsbKAfs+RD0MRl1q/Vlt2DSbvUCjOikuvXMzrGwbvyJjR2hXSK5FzR36zIwfQmxs+hg0=
